[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.33"
clap = { version = "4.5.13", features = ["derive"] }
crossterm = "0.27.0"
ego-tree = "0.6.2"
oneshot = "0.1.8"
portable-pty = "0.8.1"
ratatui = "0.27.0"
tui-term = "0.1.12"
include_dir = "0.7.4"
tempdir = "0.3.7"
serde = { version = "1.0.205", features = ["derive"] }
toml = "0.8.19"
which = "6.0.2"

[[bin]]
name = "linutil"
path = "src/main.rs"
