name = "Gaming"

[[data]]
name = "Arc Raiders"

[[data.entries]]
name = "Faster Matches and Config Optimizations"
description = "This shortens the videos for transitions in matches and also loads a optimized configuration file for VRR and removing motion blur and other nasty settings"
script = "arc-raiders/config-setup.sh"
task_list = "FM"

[[data]]
name = "Diablo II Resurrected"

[[data.entries]]
name = "Loot Filter"
description = "This is a loot filter for Diablo II Resurrected. It's designed to be a simple, clean, and easy to read loot filter that highlights the most important items. Works on battle.net and single player. No frills, no config, just highlights high runes and other valuable items. For more information visit: https://github.com/ChrisTitusTech/d2r-loot-filter"
script = "diablo-ii/d2r-loot-filters.sh"
task_list = "FM"

[[data]]
name = "Fallout 76"

[[data.entries]]
name = "Fallout 76 Custom INI"
description = "This script will add a Custom Fallout 76 INI file that improves performance and stability. It also includes some quality of life improvements."
script = "fallout-76/fallout76settings.sh"
task_list = "FM"

[[data]]
name = "Multi System Emulators"

[[data.entries]]
name = "RetroArch Game Emulator"
description = "Frontend for emulators, game engines and media players. NO Games or Bios' are included"
script = "emulators/retroarch.sh"
task_list = "FM"

[[data]]
name = "Nintendo Emulators"

# [[data.entries]]
# name = "Mesen 2"
# description = "NES and SNES Emulator. NO Games are included"
# script = "emulators/nintendo/mesen2.sh"
# task_list = "FM"

[[data.entries]]
name = "snes9x"
description = "Super Nintendo Emulator. NO Games are included"
script = "emulators/nintendo/snes9x.sh"
task_list = "FM"

[[data.entries]]
name = "bsnes"
description = "Super Nintendo Emulator. NO Games are included"
script = "emulators/nintendo/bsnes.sh"
task_list = "FM"

[[data.entries]]
name = "mGBA"
description = "Nintendo Game Boy Advance Emulator. NO Games are included"
script = "emulators/nintendo/mgba.sh"
task_list = "FM"

[[data.entries]]
name = "Mupen 64 Plus"
description = "N64 Emulator. NO Games are included"
script = "emulators/nintendo/mupen64plus.sh"
task_list = "FM"

[[data.entries]]
name = "Gopher 64"
description = "N64 Emulator. NO Games are included"
script = "emulators/nintendo/gopher64.sh"
task_list = "FM"

[[data.entries]]
name = "Dolphin Emulator"
description = "GameCube and Wii Emulator. NO Games are included"
script = "emulators/nintendo/dolphin-emu.sh"
task_list = "FM"

[[data.entries]]
name = "MelonDS"
description = "Nintendo DS and DSi Emulator. NO Games are included"
script = "emulators/nintendo/melonds.sh"
task_list = "FM"

[[data.entries]]
name = "Ryujinx"
description = "Nintendo Switch emulator. NO Games are included"
script = "emulators/nintendo/ryujinx.sh"
task_list = "FM"

[[data]]
name = "Playstation Emulators"

# [[data.entries]]
# name = "PCSX"
# description = "A Playstation emulator. NO Games or Bios' are included"
# script = "emulators/playstation/pcsx.sh"
# task_list = "FM"

[[data.entries]]
name = "PCSX2"
description = "A Playstation 2 emulator. NO Games or Bios' are included"
script = "emulators/playstation/pcsx2.sh"
task_list = "FM"

[[data.entries]]
name = "Play!"
description = "An Experimental Playstation 2 emulator. NO Games or Bios' are included"
script = "emulators/playstation/play-emu.sh"
task_list = "FM"

[[data.entries]]
name = "RPCS3"
description = "A Playstation 3 emulator. NO Games or Bios' are included"
script = "emulators/playstation/rpcs3.sh"
task_list = "FM"

[[data]]
name = "Xbox Emulators"

[[data.entries]]
name = "XEMU"
description = "An Original Xbox emulator. NO Games or Bios' are included"
script = "emulators/xbox/xemu.sh"
task_list = "FM"

[[data.entries]]
name = "Xenia"
description = "An Experimental Xbox 360 emulator. NO Games or Bios' are included"
script = "emulators/xbox/xenia.sh"
task_list = "FM"

[[data]]
name = "Sega Emulators"

[[data.entries]]
name = "Blastem"
description = "A Genesis emulator. NO Games are included"
script = "emulators/sega/blastem.sh"
task_list = "FM"

# [[data.entries]]
# name = "Yabause"
# description = "A Sega Saturn emulator"
# script = "emulators/sega/yabause.sh"
# task_list = "FM"

[[data.entries]]
name = "Kronos"
description = "A Sega Saturn emulator. NO Games are included"
script = "emulators/sega/kronos.sh"
task_list = "FM"

[[data.entries]]
name = "Flycast"
description = "A Dreamcase emulator. NO Games are included"
script = "emulators/sega/flycast.sh"
task_list = "FM"