name = "System Setup"
multi_selectable = false

[[data]]
name = "Arch Linux"

[[data.preconditions]]
matches = true
data = "command_exists"
values = ["pacman"]

[[data.entries]]
name = "Arch Server Setup"
description = "This command installs a minimal arch server setup under 5 minutes."
script = "arch/server-setup.sh"
task_list = "SI D"

[[data.entries]]
name = "Paru AUR Helper"
description = "Paru is your standard pacman wrapping AUR helper with lots of features and minimal interaction.\nTo know more about AUR helpers visit: https://wiki.archlinux.org/title/AUR_helpers"
script = "arch/paru-setup.sh"
task_list = "I"

[[data.entries]]
name = "Yay AUR Helper"
description = "Yet Another Yogurt - An AUR Helper Written in Go.\nTo know more about AUR helpers visit: https://wiki.archlinux.org/title/AUR_helpers"
script = "arch/yay-setup.sh"
task_list = "I"

[[data]]
name = "Fedora"

[[data.preconditions]]
matches = true
data = "command_exists"
values = ["dnf"]

[[data.entries]]
name = "Configure DNF"
description = "Optimizes DNF for parallel downloads"
script = "fedora/configure-dnf.sh"
task_list = "PFM"

[[data.entries]]
name = "Multimedia Codecs"
description = "This script is designed to install multimedia codecs, and to ensure RPM Fusion repositories are installed."
script = "fedora/multimedia-codecs.sh"
task_list = "I"

[[data.entries]]
name = "Nvidia Proprietary Drivers"
description = "This script is designed to download the proprietary NVIDIA drivers in Fedora."
script = "fedora/nvidia-proprietary-driver-setup.sh"
task_list = "I"

[[data.entries]]
name = "RPM Fusion"
description = "RPM Fusion provides software that the Fedora Project or Red Hat doesn't want to ship.\nThat software is provided as precompiled RPMs for all current Fedora versions and current Red Hat Enterprise Linux or clones versions; you can use the RPM Fusion repositories with tools like yum and PackageKit.\nFor more information visit: https://rpmfusion.org/"
script = "fedora/rpm-fusion-setup.sh"
task_list = "MP"

[[data.entries]]
name = "Virtualization"
description = "Enables Virtualization through dnf"
script = "fedora/virtualization.sh"
task_list = "I"

[[data]]
name = "Build Prerequisites"
description = "This script is designed to handle the installation of various software dependencies across different Linux distributions"
script = "compile-setup.sh"
task_list = "I"

[[data]]
name = "Full System Cleanup"
description = "This script is designed to remove unnecessary packages, clean old cache files, remove temporary files, and to empty the trash."
script = "system-cleanup.sh"
task_list = "RP PFM"

[[data]]
name = "Full System Update"
description = "This command updates your system to the latest packages available for your distro"
script = "system-update.sh"
task_list = "PFM"

[[data]]
name = "Gaming Dependencies"
description = "This script is designed to handle the installation of gaming dependencies across different Linux distributions"
script = "gaming-setup.sh"
task_list = "I"

[[data]]
name = "Global Theme"
description = "This script is designed to handle the installation and configuration of global theming"
script = "global-theme.sh"
task_list = "I PFM"

[[data]]
name = "Remove Snaps"
description = "This script is designed to remove snap"
script = "remove-snaps.sh"
task_list = "RP"

[[data]]
name = "TTY Fonts"
description = "This Script will set the default TTY font to Terminus size 32 Bold"
script = "terminus-tty.sh"
task_list = "I PFM"
