name: Check for bashisms

on:
  pull_request:
    paths:
      - core/tabs/**
  merge_group:
  workflow_dispatch:

jobs:
  check-bashisms:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin ${{ github.base_ref }}

      - name: Get a list of changed script files
        id: get_sh_files
        run: |
          sh_files=$(git diff --name-only origin/${{ github.base_ref }} HEAD core/tabs | grep '\.sh$' || true)
          echo "::set-output name=sh_files::$sh_files"
      
      - name: Install devscripts
        if: steps.get_sh_files.outputs.sh_files != ""
        run: sudo apt-get update && sudo apt-get install devscripts

      - name: Check for bashisms
        if: steps.get_sh_files.outputs.sh_files != ""
        run: |
          for file in ${{ steps.get_sh_files.outputs.sh_files }}; do
              if [[ -f "$file" ]]; then
                  checkbashisms "$file"
              fi
          done
