name: Issue slash commands

on:
  issue_comment:
    types: [created, edited]

jobs:
  issueCommands:
    # Skip this job if the comment was created/edited on a PR
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: none
      contents: read

    steps:
      - run: echo "command=false" >> $GITHUB_ENV

      - name: Check for /label command
        id: check_label_command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT_BODY" == *"/label"* ]]; then
            echo "command=true" >> $GITHUB_ENV
            LABEL_NAME=$(echo "$COMMENT_BODY" | awk -F"/label" '/\/label/ { match($2, /'\''([^'\'']*)'\''/, arr); if (arr[1] != "") print arr[1] }')
            echo "label_command=true" >> $GITHUB_ENV
            {
              echo "label_name<<EOF"
              echo "$LABEL_NAME"
              echo "EOF"
            } >> $GITHUB_ENV
          else
            echo "label_command=false" >> $GITHUB_ENV
          fi

      - name: Check for /unlabel command
        id: check_unlabel_command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT_BODY" == *"/unlabel"* ]]; then
            echo "command=true" >> $GITHUB_ENV
            UNLABEL_NAME=$(echo "$COMMENT_BODY" | awk -F"/unlabel" '/\/unlabel/ { match($2, /'\''([^'\'']*)'\''/, arr); if (arr[1] != "") print arr[1] }')
            echo "unlabel_command=true" >> $GITHUB_ENV
            {
              echo "unlabel_name<<EOF"
              echo "$UNLABEL_NAME"
              echo "EOF"
            } >> $GITHUB_ENV
          else
            echo "unlabel_command=false" >> $GITHUB_ENV
          fi

      - name: Check for /close command
        id: check_close_command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT_BODY" == *"/close"* ]]; then
            echo "command=true" >> $GITHUB_ENV
            echo "close_command=true" >> $GITHUB_ENV
            echo "reopen_command=false" >> $GITHUB_ENV
          else
            echo "close_command=false" >> $GITHUB_ENV
          fi

      - name: Check for /open or /reopen command
        id: check_reopen_command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [[ "$COMMENT_BODY" == *"/open"* ]] || [[ "$COMMENT_BODY" == *"/reopen"* ]]; then
            echo "command=true" >> $GITHUB_ENV
            echo "reopen_command=true" >> $GITHUB_ENV
            echo "close_command=false" >> $GITHUB_ENV
          else
            echo "reopen_command=false" >> $GITHUB_ENV
          fi

      - name: Check if the user is allowed
        id: check_user
        if: env.command == 'true'
        env:
          USER_LOGIN: ${{ github.event.comment.user.login }}
        run: |
          ALLOWED_USERS=("ChrisTitusTech" "afonsofrancof" "Marterich" "MyDrift-user" "Real-MullaC" "adamperkowski" "lj3954" "jeevithakannan2")
          # Check if array contains the user safely
          if [[ " ${ALLOWED_USERS[*]} " =~ " ${USER_LOGIN} " ]]; then
            echo "user=true" >> $GITHUB_ENV
          else
            exit 0
          fi

      - name: Close issue
        if: env.close_command == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          REPO: ${{ github.repository }}
        run: |
          echo Closing the issue...
          if [[ "$COMMENT_BODY" == *"not planned"* ]]; then
            gh issue close "$ISSUE_NUMBER" --repo "$REPO" --reason 'not planned'
          else
            gh issue close "$ISSUE_NUMBER" --repo "$REPO"
          fi

      - name: Reopen issue
        if: env.reopen_command == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          echo Reopening the issue...
          gh issue reopen "$ISSUE_NUMBER" --repo "$REPO"

      - name: Label issue
        if: env.label_command == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          echo Labeling the issue...
          gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "${{ env.label_name }}"

      - name: Remove labels
        if: env.unlabel_command == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          echo Unlabeling the issue...
          gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --remove-label "${{ env.unlabel_name }}"
