name: LinUtil Preview

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["LinUtil Release"]
    types:
      - completed

jobs:
  generate_preview:
    runs-on: ubuntu-latest
    environment: linutil_env
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get latest tag
        id: latest_tag
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            return releases.data[0].tag_name;

      - name: Set tag name
        run: echo "tag_name=${{ steps.latest_tag.outputs.result }}" >> $GITHUB_ENV

      - name: Download binary
        run: |
          curl -LO "https://github.com/${{ github.repository }}/releases/download/${{ env.tag_name }}/linutil"

      - name: Set env
        run: |
          chmod +x linutil
          mkdir -p build
          mv linutil build/linutil
          echo "${{ github.workspace }}/build" >> $GITHUB_PATH
          echo "branch_name=${{ env.tag_name }}" | tr . - >> $GITHUB_ENV

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate preview with VHS
        uses: charmbracelet/vhs-action@v2
        with:
          path: .github/preview.tape

      - name: Move preview
        run: mv preview.gif .github/preview.gif

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Preview for ${{ env.tag_name }}
          branch: preview-${{ env.branch_name }}
          title: "Update preview for ${{ env.tag_name }}"
          labels: |
            documentation
          body: |
            Automated PR to update preview gif for version ${{ env.tag_name }}
            ![preview](https://raw.githubusercontent.com/${{ github.repository }}/preview-${{ env.branch_name }}/.github/preview.gif)
        if: success()
