name: XTask Checks
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "xtask"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo"
      - "core/tabs"
      - "docs"
  push:
    paths:
      - "xtask"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo"
      - "core/tabs"
      - "docs"

env:
  CARGO_TERM_COLOR: always

jobs:
  docgen:
    name: DocGen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@0b1efab # stable

      - name: Cache Cargo registry
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-index-

      - name: Run cargo xtask docgen
        run: cargo xtask docgen

      - name: Check uncommitted documentation changes
        run: |
          if [[ -n $(git status --porcelain docs) ]]; then
            echo "Please run 'cargo xtask docgen' and commit the changes.";
            git --no-pager diff docs/generated;
            exit 1;
          fi
